<a href="https://colab.research.google.com/github/AlisonBabeu/Week4Homework/blob/main/Copy_of_Week_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://johaknigiu.github.io/Digital-Videogame-Art-Scan-Project/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "Super Smash Bros. Melee Box Art",
  "media-type": "Box Art",
  "format": "application/pdf",
  "platform": "Nintendo GameCube",
  "publisher": "Nintendo;Hal Laboratory",
  "gameid": "Super Smash Bros. Melee",
  "creator": "Nintendo of America",
  "date": "2001",
  "objectid": "gcssbmb.pdf",
  "filename": "GcSSBMb.pdf",
  "language": "English",
  "description": "This is the packaging and accompanying box artwork for Super Smash Bros. Melee. It lists general information and features of the game intended to entice consumers as well as listing requirements and system features present for the game. This box also holds the game and instruction manual.",
  "franchise": "Super Smash Bros",
  "genre": "Mascot Fighter",
  "rights": "Material protected under copyright; Using under fair use; if this material is considered damaging or offensive to the copyright owner this material will be taken down upon request. ",
  "youtube-link": "https://www.youtube.com/watch?v=tLaQhGNFUCg",
  "reference_url": "https://johaknigiu.github.io/Digital-Videogame-Art-Scan-Project/item.html?id=gcssbmb.pdf"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://johaknigiu.github.io/Digital-Videogame-Art-Scan-Project/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "mediatype",
      "terms": {}
    },
    {
      "field": "platform",
      "terms": {
        "nintendo ds": 12,
        "nintendo gamecube": 20,
        "sega dreamcast": 15,
        "sega genesis": 11,
        "sega genesis/cd": 3
      }
    },
    {
      "field": "publisher",
      "terms": {
        "amusmant vision": 3,
        "chunsoft": 3,
        "factor 5": 1,
        "factor 6": 1,
        "factor 7": 1,
        "game freak": 3,
        "hal laboratory": 3,
        "lucasarts": 3,
        "nintendo": 29,
        "sega": 29,
        "the pokemon company": 6,
        "virgin interactive": 3
      }
    },
    {
      "field": "gameid",
      "terms": {
        "animal crossing": 4,
        "animal crossing wild world": 3,
        "arnold palmer's tournament golf": 2,
        "caesar's palace": 3,
        "fzero gx": 3,
        "mario kart ds": 3,
        "phantasy star online ver. 2": 3,
        "pokemon mystery dungeon: explorers of sky": 3,
        "pokemon platinum version": 3,
        "sega marine fishing": 3,
        "sega sports world series baseball 2k2": 3,
        "sonic adventure": 3,
        "sonic adventure 2": 3,
        "sonic cd": 3,
        "sonic the hedgehog": 3,
        "sonic the hedgehog 3": 3,
        "star wars rogue leader rogue squadron ii": 3,
        "super mario sunshine": 3,
        "super smash bros. melee": 3,
        "system": 1,
        "the legend of zelda twilight princess": 3
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- mediatype
- platform
- publisher
- gameid

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below


This facet that shows up the most is publisher it is used 85 times on my selected site.

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized= pd.json_normalize(cb_data['objects'])
cb_normalized

,title,media-type,format,platform,publisher,gameid,creator,date,objectid,filename,language,description,franchise,genre,rights,youtube-link,internetarchivelink,reference_url
0,Arnold Palmer's Tournament Golf Box Art,Box Art,application/pdf,Sega Genesis,Sega,Arnold Palmer's Tournament Golf,Sega of America,1989,sgaptgb.pdf,SgAPTGb.pdf,English,This is the packaging and accompanying box art...,N/A,Sports,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=FkVJ7ES_y30,https://archive.org/details/Arnold_Palmer_Tour...,https://johaknigiu.github.io/Digital-Videogame...
1,Sonic the Hedgehog Box Art,Box Art,application/pdf,Sega Genesis,Sega,Sonic the Hedgehog,Sega of America;Greg Martin,1991; 1992,sgsthb.pdf,SgSTHb.pdf,English,This is the packaging and accompanying box art...,Sonic the Hedgehog,Platform;Action,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=BETxNmSMNMc&li...,https://archive.org/details/sonic1_bin,https://johaknigiu.github.io/Digital-Videogame...
2,Caesar's Palace Box Art,Box Art,application/pdf,Sega Genesis,Virgin Interactive,Caesar's Palace,Virgin Interactive,1993,sgcpb.pdf,SgCPb.pdf,English,This is the packaging and accompanying box art...,Caesar's Palace,Gambling,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=Mg0W1kE_pzs,NaN,https://johaknigiu.github.io/Digital-Videogame...
3,Sonic the Hedgehog 3 Box Art,Box Art,application/pdf,Sega Genesis,Sega,Sonic the Hedgehog 3,Sega of America;Greg Martin,1994,sgsth3b.pdf,SgSTH3b.pdf,English,This is the packaging and accompanying box art...,Sonic the Hedgehog,Platform;Action,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=Q260BqrWHgo,https://archive.org/details/sonic_bin,https://johaknigiu.github.io/Digital-Videogame...
4,Sonic CD Box Art,Box Art,application/pdf,Sega Genesis/CD,Sega,Sonic CD,Sega of America;Greg Martin,1993,sgscdb.pdf,SgSCDb.pdf,English,This is the packaging and accompanying box art...,Sonic the Hedgehog,Platform;Action,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=ct6hfxnShDE,NaN,https://johaknigiu.github.io/Digital-Videogame...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Pokemon Mystery Dungeon: Explorers of Sky Cart...,Cartridge,image/jpeg,Nintendo DS,Chunsoft;The Pokemon Company;Nintendo,Pokemon Mystery Dungeon: Explorers of Sky,The Pokemon Company;Nintendo of America,2009,dspmdeosc.jpg,DsPMDEOSc.jpg,English,This is the physical storage cartridge for Pok...,Pokemon; Pokemon Mystery Dungeon,Japanese RPG;Rogue-Like,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=32rPL935tgI,NaN,https://johaknigiu.github.io/Digital-Videogame...
57,Mario Kart DS Manual,Manual,application/pdf,Nintendo DS,Nintendo,Mario Kart DS,Nintendo of America,2005,dsmkdsm.pdf,DsMKDSm.pdf,English,This is the instruction manual for Mario Kart ...,Super Mario Bros; Mario Kart,Racing,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=CJ-xwo5TvH0,NaN,https://johaknigiu.github.io/Digital-Videogame...
58,Animal Crossing Wild World Manual,Manual,application/pdf,Nintendo DS,Nintendo,Animal Crossing Wild World,Nintendo of America,2005,dsacwwm.pdf,DsACWWm.pdf,English,This is the instruction manual for Animal Cros...,Animal Crossing,Social Simulator,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=rhn4kNkrX48,NaN,https://johaknigiu.github.io/Digital-Videogame...
59,Pokemon Platinum Version Manual,Manual,application/pdf,Nintendo DS,Nintendo;Game Freak;The Pokemon Company,Pokemon Platinum Version,Ken Sugamori;Game Freak;The Pokemon Company;Ni...,2009,dsppvm.pdf,DsPPVm.pdf,English,This is the instruction manual for Pokemon Pla...,Pokemon,Japanese RPG,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=w5VyM7S56GU,NaN,https://johaknigiu.github.io/Digital-Videogame...
60,Pokemon Mystery Dungeon: Explorers of Sky Manual,Manual,application/pdf,Nintendo DS,Chunsoft;The Pokemon Company; Nintendo,Pokemon Mystery Dungeon: Explorers of Sky,Ken Sugamori;Chun Soft;The Pokemon Company;Nin...,2009,dspmdeosm.pdf,DsPMDEOSm.pdf,English,This is the instruction manual for Pokemon Mys...,Pokemon; Pokemon Mystery Dungeon,Japanese RPG;Rogue-Like,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=32rPL935tgI,NaN,https://johaknigiu.github.io/Digital-Videogame...

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,media-type,format,platform,publisher,gameid,creator,date,objectid,filename,language,description,franchise,genre,rights,youtube-link,internetarchivelink,reference_url
0,Arnold Palmer's Tournament Golf Box Art,Box Art,application/pdf,Sega Genesis,Sega,Arnold Palmer's Tournament Golf,Sega of America,1989,sgaptgb.pdf,SgAPTGb.pdf,English,This is the packaging and accompanying box art...,N/A,Sports,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=FkVJ7ES_y30,https://archive.org/details/Arnold_Palmer_Tour...,https://johaknigiu.github.io/Digital-Videogame...
49,Mario Kart DS Box Art,Box Art,application/pdf,Nintendo DS,Nintendo,Mario Kart DS,Nintendo of America,2005,dsmkdsb.pdf,DsMKDSb.pdf,English,This is the packaging and accompanying box art...,Super Mario Bros; Mario Kart,Racing,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=CJ-xwo5TvH0,NaN,https://johaknigiu.github.io/Digital-Videogame...
39,FZero GX Disc,Disc,image/jpeg,Nintendo GameCube,Nintendo;Amusmant Vision;Sega,FZero GX,Nintendo of America,2003,gcfzgxd.jpg,GcFZGXd.jpg,English,This is the optical storage disc for FZero GX....,FZero,Racing,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=8hjXXupZ3iU,NaN,https://johaknigiu.github.io/Digital-Videogame...
50,Animal Crossing Wild World Box Art,Box Art,application/pdf,Nintendo DS,Nintendo,Animal Crossing Wild World,Nintendo of America,2005,dsacwwb.pdf,DsACWWb.pdf,English,This is the packaging and accompanying box art...,Animal Crossing,Social Simulator,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=rhn4kNkrX48,NaN,https://johaknigiu.github.io/Digital-Videogame...
30,Star Wars Rogue Leader Rogue Squadron II Box Art,Box Art,application/pdf,Nintendo GameCube,LucasArts;Factor 5,Star Wars Rogue Leader Rogue Squadron II,Blind Mice Studios,2001,gcswrlrsiib.pdf,GcSWRLRSIIb.pdf,English,This is the packaging and accompanying box art...,Star Wars Rogue Squadron,Flight Simulator,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=uXpi-Yybv-k,NaN,https://johaknigiu.github.io/Digital-Videogame...
20,Sega Sports World Series Baseball 2K2 Disc,Disc,image/jpeg,Sega Dreamcast,Sega,Sega Sports World Series Baseball 2K2,Sega of America,2001,dcsswsb2k2d.jpg,DcSSWSB2K2d.jpg,English,This is the optical storage disc for Sega Spor...,Sega Sports,Sports,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=mUI-xjEOUT0,NaN,https://johaknigiu.github.io/Digital-Videogame...
1,Sonic the Hedgehog Box Art,Box Art,application/pdf,Sega Genesis,Sega,Sonic the Hedgehog,Sega of America;Greg Martin,1991; 1992,sgsthb.pdf,SgSTHb.pdf,English,This is the packaging and accompanying box art...,Sonic the Hedgehog,Platform;Action,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=BETxNmSMNMc&li...,https://archive.org/details/sonic1_bin,https://johaknigiu.github.io/Digital-Videogame...
33,FZero GX Box Art,Box Art,application/pdf,Nintendo GameCube,Nintendo;Amusmant Vision;Sega,FZero GX,Nintendo of America,2003,gcfzgxb.pdf,GcFZGXb.pdf,English,This is the packaging and accompanying box art...,FZero,Racing,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=8hjXXupZ3iU,NaN,https://johaknigiu.github.io/Digital-Videogame...
42,Star Wars Rogue Leader Rogue Squadron II Manual,Manual,application/pdf,Nintendo GameCube,LucasArts;Factor 7,Star Wars Rogue Leader Rogue Squadron II,Geoff Keighley;Tom Byron;Logan Parr;Blind Mice...,2001,gcswrlrsiim.pdf,GcSWRLRSIIm.pdf,English,This is the instruction manual for Star Wars R...,Star Wars Rogue Squadron,Flight Simulator,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=uXpi-Yybv-k,NaN,https://johaknigiu.github.io/Digital-Videogame...
11,Caesar's Palace Manual,Manual,application/pdf,Sega Genesis,Virgin Interactive,Caesar's Palace,Cathie A. Todd;Michael Winfield;Lisa Marcinko,1993,sgcpm.pdf,SgCPm.pdf,English,This is the instruction manual for Caesar's Pa...,Caesar's Palace,Gambling,Material protected under copyright; Using unde...,https://www.youtube.com/watch?v=Mg0W1kE_pzs,NaN,https://johaknigiu.github.io/Digital-Videogame...

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
cb_normalized["publisher"].value_counts()
# I could not seem to figure out a way to just count how many times publisher
#occurs, so I thought I would try for the top values in the publisher facet.

publisher
Sega                                        26
Nintendo                                    17
Virgin Interactive                           3
Nintendo;Hal Laboratory                      3
Nintendo;Amusmant Vision;Sega                3
Nintendo;Game Freak;The Pokemon Company      3
Chunsoft;The Pokemon Company;Nintendo        2
LucasArts;Factor 6                           1
LucasArts;Factor 5                           1
LucasArts;Factor 7                           1
Chunsoft;The Pokemon Company; Nintendo       1
Name: count, dtype: int64


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.